#! /bin/bash

scripts=$(find . -type f ! -path '*/\.*' \( -executable -o -name '*.py' \) -exec grep -lE '^#! *(|/usr/bin/env +|/bin/|/usr/bin/)(python|python3)' {} +)

set -e

fatal() {
  echo "$@"
  exit 1
}

# Locate pyflakes.
for cmd in pyflakes3 pyflakes; do
  if which "$cmd" 2>/dev/null; then
    pyflakes=$(which "$cmd")
    break
  fi
done
if [[ -z "$pyflakes" ]]; then
  fatal "Could not find pyflakes"
fi

echo "Running pyflakes on the following scripts:"
echo "$scripts"
errors=0
for script in $scripts; do
  if ! $pyflakes "$script"; then
    errors=$((errors + 1))
  fi
done
if [ "$errors" -ne 0 ]; then
  fatal "pyflakes found issues."
fi
echo "pyflakes passed successfully."
